### ISSUE TITLE
Badge Printing Page Gives 500

### ISSUE THREAD

**Issue by jmdawson** [MidwestFurryFandom/rams#157]
Loads the main badge_printing page fine, but then throws a 500 on the badge_waiting page
`Traceback (most recent call last):
  File "/app/env/lib/python3.4/site-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/app/env/lib/python3.4/site-packages/cherrypy/lib/encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/app/env/lib/python3.4/site-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/app/plugins/uber/uber/decorators.py", line 238, in with_timing
    return func(*args, **kwargs)
  File "/app/plugins/uber/uber/decorators.py", line 229, in with_caching
    return func(*args, **kwargs)
  File "/app/plugins/uber/uber/decorators.py", line 253, in with_session
    retval = func(*args, session=session, **kwargs)
  File "/app/plugins/uber/uber/decorators.py", line 387, in with_restrictions
    return func(*args, **kwargs)
  File "/app/plugins/uber/uber/decorators.py", line 353, in with_rendering
    return render(_get_template_filename(func), result)
  File "/app/plugins/uber/uber/decorators.py", line 273, in render
    template = env.get_or_select_template(template_name_list)
  File "/app/env/lib/python3.4/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/app/env/lib/python3.4/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/app/env/lib/python3.4/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/app/env/lib/python3.4/site-packages/jinja2/loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "/app/env/lib/python3.4/site-packages/jinja2/environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "/app/env/lib/python3.4/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/app/env/lib/python3.4/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/app/plugins/badge_printing/badge_printing/templates/kiosk_printing/print_badges.html", line 51, in template
    <span id="badge_num">2015-{{ badge_num|stringformat:"04d" }}</span>
  File "/app/env/lib/python3.4/site-packages/jinja2/environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "/app/env/lib/python3.4/site-packages/jinja2/parser.py", line 896, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "/app/env/lib/python3.4/site-packages/jinja2/parser.py", line 871, in subparse
    self.stream.expect('variable_end')
  File "/app/env/lib/python3.4/site-packages/jinja2/lexer.py", line 386, in expect
    self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: expected token 'end of print statement', got ':'`

**Comment by jmdawson** [comment]
Start page: http://localhost/rams/kiosk_printing/badge_waiting
End page: http://localhost/rams/kiosk_printing/print_badges?minor=

**Comment by kitsuta** [comment]
This was an error from an old tag, which has since been updated. Given that @jmdawson tested this again recently and noted that the badge number was prepended by "2015," I believe this error is now fixed.
