### ISSUE TITLE
Stripe throws an error w/ receipt email

### ISSUE THREAD

**Issue by jmdawson** [MidwestFurryFandom/rams#168]
`Got an error while calling charge_cc(self, token='tok_REDACTED')
Traceback (most recent call last):
 File "/app/plugins/uber/uber/utils.py", line 335, in charge_cc
   receipt_email=self.receipt_email
 File "/app/env/lib/python3.4/site-packages/stripe/resource.py", line 258, in create
   response, api_key = requestor.request('post', url, params)
 File "/app/env/lib/python3.4/site-packages/stripe/api_requestor.py", line 124, in request
   resp = self.interpret_response(rbody, rcode)
 File "/app/env/lib/python3.4/site-packages/stripe/api_requestor.py", line 228, in interpret_response
   self.handle_api_error(rbody, rcode, resp)
 File "/app/env/lib/python3.4/site-packages/stripe/api_requestor.py", line 138, in handle_api_error
   err.get('message'), err.get('param'), rbody, rcode, resp)
stripe.error.InvalidRequestError: Invalid positive integer`

**Comment by jmdawson** [comment]
Stale. Stripe integration is really different now.
