### ISSUE TITLE
Badge printing error

### ISSUE THREAD

**Issue by ianlayton** [MidwestFurryFandom/rams#193]
This was working last week...now when I go to the page to print badges I get:

Traceback (most recent call last):
  File "/app/env/lib/python3.4/site-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/app/env/lib/python3.4/site-packages/cherrypy/lib/encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/app/env/lib/python3.4/site-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/app/plugins/uber/uber/decorators.py", line 238, in with_timing
    return func(*args, **kwargs)
  File "/app/plugins/uber/uber/decorators.py", line 229, in with_caching
    return func(*args, **kwargs)
  File "/app/plugins/uber/uber/decorators.py", line 253, in with_session
    retval = func(*args, session=session, **kwargs)
  File "/app/plugins/uber/uber/decorators.py", line 387, in with_restrictions
    return func(*args, **kwargs)
  File "/app/plugins/uber/uber/decorators.py", line 349, in with_rendering
    result = func(*args, **kwargs)
  File "/app/plugins/badge_printing/badge_printing/site_sections/kiosk_printing.py", line 36, in print_badges
    badge_list = [row for row in badge_list if c.AGE_GROUP_CONFIGS[row.age_group]['min_age'] < 18] if minor else [row for row in badge_list if c.AGE_GROUP_CONFIGS[row.age_group]['min_age'] >= 18]
  File "/app/plugins/badge_printing/badge_printing/site_sections/kiosk_printing.py", line 36, in <listcomp>
    badge_list = [row for row in badge_list if c.AGE_GROUP_CONFIGS[row.age_group]['min_age'] < 18] if minor else [row for row in badge_list if c.AGE_GROUP_CONFIGS[row.age_group]['min_age'] >= 18]
KeyError: 'min_age'

**Comment by kitsuta** [comment]
Is this on the staging server or the production server?

**Comment by ianlayton** [comment]
Staging

**Comment by ianlayton** [comment]
Any idea on the cause of this please...this is another item I need to have working so I can I finish my testing.

thank you.

**Comment by ianlayton** [comment]
Still waiting on an update on this please.

**Comment by kitsuta** [comment]
Hm, unfortunately I haven't really made any progress wrt figuring out what causes this... I'm gonna change tactics and rewrite the function in question so that this kind of error doesn't kill the printing process.

**Comment by ianlayton** [comment]
the funny thing was...this was working week before last when I was doing some testing

**Comment by kitsuta** [comment]
Yeah, the problem is intermittent, which is making it really tricky to track down. I thought we had gotten rid of it by a recent change, but it appears not.

**Comment by kitsuta** [comment]
OK, completely overhauled the way we select badges for printing. This specific error will never hit us again; we no longer use the `c.AGE_GROUP_CONFIGS` to sort the badges.

**Comment by ianlayton** [comment]
New error on staging:

Traceback (most recent call last):
  File "/app/env/lib/python3.4/site-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/app/env/lib/python3.4/site-packages/cherrypy/lib/encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/app/env/lib/python3.4/site-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/app/plugins/uber/uber/decorators.py", line 238, in with_timing
    return func(*args, **kwargs)
  File "/app/plugins/uber/uber/decorators.py", line 229, in with_caching
    return func(*args, **kwargs)
  File "/app/plugins/uber/uber/decorators.py", line 253, in with_session
    retval = func(*args, session=session, **kwargs)
  File "/app/plugins/uber/uber/decorators.py", line 387, in with_restrictions
    return func(*args, **kwargs)
  File "/app/plugins/uber/uber/decorators.py", line 349, in with_rendering
    result = func(*args, **kwargs)
  File "/app/plugins/badge_printing/badge_printing/site_sections/kiosk_printing.py", line 42, in print_badges
    attendee = next(badge for badge in badge_list if badge.age_now_or_at_con >= 18)
StopIteration

**Comment by kitsuta** [comment]
Whoops! This error's much easier. Will have a fix in-code soon.

**Comment by ianlayton** [comment]
Anu update on when this will be pushed please.

**Comment by kitsuta** [comment]
This is already fixed on staging.

**Comment by ianlayton** [comment]
Thank you...sorry for that. Last time I had checked (I think Friday) it hadn't been pushed. I'll make sure to double check on stuff before bugging you again. :)

**Comment by ianlayton** [comment]
And seems to be good now. No errors when printing.
