### ISSUE TITLE
Duplicate badge ID being issued

### ISSUE THREAD

**Issue by ianlayton** [MidwestFurryFandom/rams#333]
Appears a race condition is being hit, getting some emails from people saying that they had this error:

Error was "Key (badge num) 5074 already exists" 

Someone else sent the following error:

Traceback (most recent call last): File "/app/env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 724, in _commit_impl self.engine.dialect.do_commit(self.connection) File "/app/env/lib/python3.4/site-packages/sqlalchemy/engine/default.py", line 460, in do_commit dbapi_connection.commit() psycopg2.IntegrityError: duplicate key value violates unique constraint "uq_attendee_badge_num" DETAIL: Key (badge_num)=(5324) already exists. The above exception was the direct cause of the following exception: Traceback (most recent call last): File "/app/plugins/uber/uber/decorators.py", line 358, in charge return func(self, session=session, payment_id=payment_id, stripeToken=stripeToken) File "/app/plugins/uber/uber/site_sections/preregistration.py", line 393, in prereg_payment session.commit() # paranoia: really make sure we lock in marking taking payments in the database File "/app/env/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 943, in commit self.transaction.commit() File "/app/env/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 471, in commit t[1].commit() File "/app/env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1643, in commit self._do_commit() File "/app/env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1674, in _do_commit self.connection._commit_impl() File "/app/env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 726, in _commit_impl self._handle_dbapi_exception(e, None, None, None, None) File "/app/env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception exc_info File "/app/env/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause reraise(type(exception), exception, tb=exc_tb, cause=cause) File "/app/env/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 186, in reraise raise value.with_traceback(tb) File "/app/env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 724, in _commit_impl self.engine.dialect.do_commit(self.connection) File "/app/env/lib/python3.4/site-packages/sqlalchemy/engine/default.py", line 460, in do_commit dbapi_connection.commit() sqlalchemy.exc.IntegrityError: (psycopg2.IntegrityError) duplicate key value violates unique constraint "uq_attendee_badge_num" DETAIL: Key (badge_num)=(5324) already exists. (Background on this error at: http://sqlalche.me/e/gkpj)

**Comment by kitsuta** [comment]
The good news is, this is super rare.

The bad news is, this is _super rare_.

We've had this crop up before and have attempted to fix it (I rewrote that entire set of functions, and then MAGFest's full-time senior engineer at the time _also_ completely rewrote them), and that clearly hasn't worked. I'll need more information, and that will probably involve investigating the badges this has happened to thus far for MFF.

**Comment by ianlayton** [comment]
I sent Crimson a list of transactions in Stripe that didn't have matching transactions in RAMS last night, so that should give you names of the affected people. Their information is stored in the database change log, but I'm not able to find them in the attendee table export that I have available. Not sure if that's because unfinished badges are cleared out after X time or the export script ignores badges in that state.

**Comment by kitsuta** [comment]
The duplicate badge bug occurs when trying to insert the badge into the database, so unfortunately when it fails we end up with no badge. They'll need to be created manually.

**Comment by SkylerRingtail** [comment]
Tangential note: should we be dumping such a detailed Traceback to attendees? Or giving them the database error "Key (badge num) 5074 already exists" that reveals part of the structure (the key column) of our underlying database? This strikes me as a potential security risk.

**Comment by kitsuta** [comment]
There's no personal data in these stacktraces, just a _lot_ of function calls.

**Comment by jmdawson** [comment]
There's not much you can do w/ a badge number, and it doesn't tell you who has that number. The rest of it is stack traces from open-source code.
