### ISSUE TITLE
500 Error on submit Art Show Application

### ISSUE THREAD

**Issue by jmdawson** [MidwestFurryFandom/rams#435]
In production (but not in staging), users who submit an art show application get a 500 error, and no application is recorded in the system.

```
ESC[36mweb_1            |ESC[0m 2021-09-29T17:01:02.214402722Z     Traceback (most recent call last):
ESC[36mweb_1            |ESC[0m 2021-09-29T17:01:02.214406761Z       File "/app/env/lib/python3.6/site-packages/cherrypy/_cprequest.py", line 630, in respond
ESC[36mweb_1            |ESC[0m 2021-09-29T17:01:02.214410981Z         self._do_respond(path_info)
ESC[36mweb_1            |ESC[0m 2021-09-29T17:01:02.214414914Z       File "/app/env/lib/python3.6/site-packages/cherrypy/_cprequest.py", line 689, in _do_respond
ESC[36mweb_1            |ESC[0m 2021-09-29T17:01:02.214419111Z         response.body = self.handler()
ESC[36mweb_1            |ESC[0m 2021-09-29T17:01:02.214423841Z       File "/app/env/lib/python3.6/site-packages/cherrypy/lib/encoding.py", line 221, in __call__
ESC[36mweb_1            |ESC[0m 2021-09-29T17:01:02.214428049Z         self.body = self.oldhandler(*args, **kwargs)
ESC[36mweb_1            |ESC[0m 2021-09-29T17:01:02.214432021Z       File "/app/env/lib/python3.6/site-packages/cherrypy/_cpdispatch.py", line 54, in __call__
ESC[36mweb_1            |ESC[0m 2021-09-29T17:01:02.214436128Z         return self.callable(*self.args, **self.kwargs)
ESC[36mweb_1            |ESC[0m 2021-09-29T17:01:02.214440199Z       File "/app/plugins/uber/uber/decorators.py", line 510, in with_timed
ESC[36mweb_1            |ESC[0m 2021-09-29T17:01:02.214444303Z         return func(*args, **kwargs)
ESC[36mweb_1            |ESC[0m 2021-09-29T17:01:02.214448286Z       File "/app/plugins/uber/uber/decorators.py", line 536, in with_session
ESC[36mweb_1            |ESC[0m 2021-09-29T17:01:02.214452418Z         retval = func(*args, session=session, **kwargs)
ESC[36mweb_1            |ESC[0m 2021-09-29T17:01:02.214456418Z       File "/app/plugins/uber/uber/decorators.py", line 685, in with_restrictions
ESC[36mweb_1            |ESC[0m 2021-09-29T17:01:02.214464281Z         return func(*args, **kwargs)
ESC[36mweb_1            |ESC[0m 2021-09-29T17:01:02.214468439Z       File "/app/plugins/uber/uber/decorators.py", line 591, in with_rendering
ESC[36mweb_1            |ESC[0m 2021-09-29T17:01:02.214472508Z         result = func(*args, **kwargs)
ESC[36mweb_1            |ESC[0m 2021-09-29T17:01:02.214476435Z       File "/app/plugins/uber/uber/site_sections/art_show_applications.py", line 52, in index
ESC[36mweb_1            |ESC[0m 2021-09-29T17:01:02.214480593Z         {'app': app}), model=app)
ESC[36mweb_1            |ESC[0m 2021-09-29T17:01:02.214484563Z       File "/app/env/lib/python3.6/site-packages/celery/local.py", line 193, in __call__
ESC[36mweb_1            |ESC[0m 2021-09-29T17:01:02.214488723Z         return self._get_current_object()(*a, **kw)
ESC[36mweb_1            |ESC[0m 2021-09-29T17:01:02.214492705Z       File "/app/env/lib/python3.6/site-packages/celery/app/task.py", line 379, in __call__
ESC[36mweb_1            |ESC[0m 2021-09-29T17:01:02.214496801Z         return self.run(*args, **kwargs)
ESC[36mweb_1            |ESC[0m 2021-09-29T17:01:02.214500755Z       File "/app/plugins/uber/uber/tasks/email.py", line 69, in send_email
ESC[36mweb_1            |ESC[0m 2021-09-29T17:01:02.214504881Z         log.error('Error while sending email: ' + error_msg)
ESC[36mweb_1            |ESC[0m 2021-09-29T17:01:02.214508860Z     TypeError: must be str, not ParamValidationError
```

**Comment by jmdawson** [comment]
I took a look, but there's no art show config in development.ini on staging that isn't in development.ini on prod.
