### ISSUE TITLE
Art Show Quick Sale 500 Error

### ISSUE THREAD

**Issue by Hugmonster** [MidwestFurryFandom/rams#468]
Need by 11/12 So I can confirm other steps after this are working correctly, before con. 

Get this when attempting to process a Quick Sale: 
http://rams.test.furfest.org/rams/art_show_admin/pieces_bought?id=76ac0af2-da9a-459c-9fe8-6581e7443f5a 

Please contact us via https://www.furfest.org if you're not sure why you're seeing this page.
500 Internal Server Error
The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/app/env/lib/python3.6/site-packages/cherrypy/_cprequest.py", line 630, in respond
    self._do_respond(path_info)
  File "/app/env/lib/python3.6/site-packages/cherrypy/_cprequest.py", line 689, in _do_respond
    response.body = self.handler()
  File "/app/env/lib/python3.6/site-packages/cherrypy/lib/encoding.py", line 221, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/app/env/lib/python3.6/site-packages/cherrypy/_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/app/plugins/uber/uber/decorators.py", line 515, in with_timed
    return func(*args, **kwargs)
  File "/app/plugins/uber/uber/decorators.py", line 541, in with_session
    retval = func(*args, session=session, **kwargs)
  File "/app/plugins/uber/uber/decorators.py", line 690, in with_restrictions
    return func(*args, **kwargs)
  File "/app/plugins/uber/uber/decorators.py", line 633, in with_rendering
    return render(_get_template_filename(func), result)
  File "/app/plugins/uber/uber/decorators.py", line 561, in render
    template = env.get_or_select_template(template_name_list)
  File "/app/plugins/uber/uber/jinja.py", line 103, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals, use_request_cache)
  File "/app/plugins/uber/uber/jinja.py", line 77, in get_template
    return self._load_template(name, self.make_globals(globals), use_request_cache)
  File "/app/plugins/uber/uber/jinja.py", line 62, in _load_template
    template = self.loader.load(self, filename, globals)
  File "/app/env/lib/python3.6/site-packages/jinja2/loaders.py", line 127, in load
    code = environment.compile(source, name, filename)
  File "/app/env/lib/python3.6/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/app/env/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/app/env/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/app/plugins/uber/uber/templates/art_show_admin/pieces_bought.html", line 120, in template
    <span class="input-group-addon">$</span><input type="text" class="form-control" id="stripe_amount" placeholder="{{ (receipt.owed / 100)format_currency }}" />
jinja2.exceptions.TemplateSyntaxError: expected token 'end of print statement', got 'format_currency'

**Comment by kitsuta** [comment]
It looks like this works now -- I'm assuming https://github.com/MidwestFurryFandom/rams/pull/462 hadn't actually made it to staging when you tested last.

**Comment by Hugmonster** [comment]
I agree that this works.
Hugmonster
Art Show Director
