### ISSUE TITLE
Art Show Bid Sheets Not Printing - Error 500 

### ISSUE THREAD

**Issue by Hugmonster** [MidwestFurryFandom/rams#469]
Need by 11/24 - So I can start printing ahead. 

When attempting to print bid sheets I get -  Might just be a missing font.    Sent font in email on 10/12.   Subject Barcode Font.

https://reg.furfest.org/rams/art_show_admin/bid_sheet_pdf

Please contact us via https://www.furfest.org if you're not sure why you're seeing this page.
500 Internal Server Error
The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/app/env/lib/python3.6/site-packages/cherrypy/_cprequest.py", line 630, in respond
    self._do_respond(path_info)
  File "/app/env/lib/python3.6/site-packages/cherrypy/_cprequest.py", line 689, in _do_respond
    response.body = self.handler()
  File "/app/env/lib/python3.6/site-packages/cherrypy/lib/encoding.py", line 221, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/app/env/lib/python3.6/site-packages/cherrypy/_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/app/plugins/uber/uber/decorators.py", line 515, in with_timed
    return func(*args, **kwargs)
  File "/app/plugins/uber/uber/decorators.py", line 541, in with_session
    retval = func(*args, session=session, **kwargs)
  File "/app/plugins/uber/uber/decorators.py", line 690, in with_restrictions
    return func(*args, **kwargs)
  File "/app/plugins/uber/uber/decorators.py", line 596, in with_rendering
    result = func(*args, **kwargs)
  File "/app/plugins/uber/uber/site_sections/art_show_admin.py", line 405, in bid_sheet_pdf
    pdf.add_font('3of9', '', os.path.join(c.MODULE_ROOT, 'static/fonts/free3of9.ttf'), uni=True)
  File "/app/env/lib/python3.6/site-packages/fpdf/fpdf.py", line 469, in add_font
    raise RuntimeError("TTF Font file not found: %s" % fname)
RuntimeError: TTF Font file not found: /app/plugins/mff-rams-plugin/mff_rams_plugin/static/fonts/free3of9.ttf

**Comment by Hugmonster** [comment]
Same error on http://rams.test.furfest.org/rams/art_show_admin/bid_sheet_pdf
