### ISSUE TITLE
Art Show Report Throwing 500 Error - Artist Information CSV

### ISSUE THREAD

**Issue by Hugmonster** [MidwestFurryFandom/rams#496]
https://reg.furfest.org/rams/art_show_reports/artist_csv 

All other reports are fine.   This report works in Test 

Please contact us via https://www.furfest.org if you're not sure why you're seeing this page.
500 Internal Server Error
The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/app/env/lib/python3.6/site-packages/cherrypy/_cprequest.py", line 630, in respond
    self._do_respond(path_info)
  File "/app/env/lib/python3.6/site-packages/cherrypy/_cprequest.py", line 689, in _do_respond
    response.body = self.handler()
  File "/app/env/lib/python3.6/site-packages/cherrypy/lib/encoding.py", line 221, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/app/env/lib/python3.6/site-packages/cherrypy/_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/app/plugins/uber/uber/decorators.py", line 515, in with_timed
    return func(*args, **kwargs)
  File "/app/plugins/uber/uber/decorators.py", line 541, in with_session
    retval = func(*args, session=session, **kwargs)
  File "/app/plugins/uber/uber/decorators.py", line 690, in with_restrictions
    return func(*args, **kwargs)
  File "/app/plugins/uber/uber/decorators.py", line 596, in with_rendering
    result = func(*args, **kwargs)
  File "/app/plugins/uber/uber/decorators.py", line 357, in csvout
    func(self, csv.writer(writer), session, **kwargs)
  File "/app/plugins/uber/uber/site_sections/art_show_reports.py", line 193, in artist_csv
    app.attendee.full_name,
AttributeError: 'NoneType' object has no attribute 'full_name'
Powered by CherryPy 17.3.0

**Comment by Hugmonster** [comment]
Issue was one application was not tied to a badge.  Works fine now
